# Generated by Django 2.0.2 on 2018-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180909_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
